on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy CloudFormation stack3
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: us-east-1
        run: |
          aws cloudformation deploy \
            --template-file ./single-tier-app.yaml \
            --stack-name my-stack3 \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides Ec2Instance=Instance
            --region us-east-1